### ISSUE TITLE
amcl process is not killed after terminating session

### ISSUE THREAD

**Issue by gpdas** [marc-hanheide/TMuLE#6]
A full stack for simulating thorvald with topological_navigation in tmule/norway_poles_sim.yaml. Launched all windows. Killed all by terminating session. amcl process was not killed.

Relevant files are available here: https://github.com/LCAS/RASberry/pull/98

1. launched using: tmule --config $(rospack find rasberry_bringup)/tmue/norway_poles_sim.yaml launch
2. termianted using: tmule --config $(rospack find rasberry_bringup)/tmue/norway_poles_sim.yaml termiante

two gazebo processes were also running, but died after some time. 
amcl node did not die and had to be killed manually.
rasberry_navigation/launch/rasberry_localisation.launch -> rasberry_move_base/launch/amcl.launch -> amcl node

**Comment by marc-hanheide** [comment]
Thanks for reporting, do you recall if the tmux session was terminated and if there were any errors on the console?

**Comment by marc-hanheide** [comment]
this should be fixed in version 1.1.9
